name: automatically add to project board
on:
    issues:
        types: [opened, transferred, reopened, unlocked]
    pull_request:
        types: [opened, edited, synchronize, auto_merge_enabled, reopened]

jobs:
    add_to_project:
        uses: road86/.github/.github/workflows/add-to-project.yml@main
        secrets:
            TOKEN: ${{ secrets.ROBOT_TOKEN }}
